export { ApiError, SESSION_UNAUTHORIZED_EVENT } from "./client";
export { getHealth, type HealthResponse } from "./health";
export {
   createAccessSession,
   deleteAccessSession,
   getCurrentSessionProfile,
   refreshCurrentSessionProfile,
   type OwnedGameResponse,
   type SessionProfileResponse,
} from "./session";
export {
   getAssistantFilterOptions,
   getAssistantGenres,
   getAssistantRecommendations,
   getFinalRecommendations,
   getReferenceKeywords,
   getReferenceDetails,
   refineFinalRecommendations,
   searchReferenceGames,
   validateRecommendationPreference,
   type AssistantFilterContextRequest,
   type AssistantFilterOptionsResponse,
   type AssistantGenreOptionsResponse,
   type AssistantOptionResponse,
   type AssistantRecommendationItemResponse,
   type AssistantRecommendationResponse,
   type AssistantRecommendationSubmission,
   type FacetOptionResponse,
   type FacetKind,
   type FacetLabelResponse,
   type FacetMatchState,
   type FactualScoreEvidenceResponse,
   type FinalRecommendationItemResponse,
   type FinalRecommendationResponse,
   type KeywordBrowseResponse,
   type OwnedGameSearchResponse,
   type OwnedGameSuggestionResponse,
   type PlayStatus,
   type PreferenceConstraints,
   type RecommendationPreference,
   type RecommendationRefinementRequest,
   type ReferenceDetailsResponse,
} from "./recommendations";
