export { ApiError, SESSION_UNAUTHORIZED_EVENT } from "./client";
export { getHealth, type HealthResponse } from "./health";
export {
   createAccessSession,
   deleteAccessSession,
   getCurrentSessionProfile,
   refreshCurrentSessionProfile,
   type OwnedGameResponse,
   type SessionProfileResponse,
} from "./session";
export {
   getFinalRecommendations,
   getReferenceKeywords,
   getReferenceDetails,
   refineFinalRecommendations,
   searchReferenceGames,
   searchReferenceKeywords,
   validateRecommendationPreference,
   type FacetOptionResponse,
   type FacetKind,
   type FacetLabelResponse,
   type FacetMatchState,
   type FactualContributionResponse,
   type FactualScoreEvidenceResponse,
   type FinalRecommendationItemResponse,
   type FinalRecommendationResponse,
   type KeywordSearchResponse,
   type KeywordBrowseResponse,
   type MetadataStatus,
   type MatchReasonResponse,
   type MatchSummaryResponse,
   type OwnedGameSearchResponse,
   type OwnedGameSuggestionResponse,
   type PlayStatus,
   type PreferenceConstraints,
   type RecommendationErrorCode,
   type RecommendationOutcome,
   type RecommendationPreference,
   type RecommendationRefinementRequest,
   type RecommendationTradeoffResponse,
   type ReferenceDetailsResponse,
   type ReferenceFacetsResponse,
   type ReferencePreference,
   type SelectedFacets,
   type UnknownCompletionTimeTradeoffResponse,
   type UnknownPreferenceMetadataTradeoffResponse,
   type UnmatchedPreferenceReasonResponse,
   type UnmatchedPreferenceTradeoffResponse,
} from "./recommendations";
