"""add game trait derivations

Revision ID: 12154eb07460
Revises: 482cd8b4ee1b
Create Date: 2026-08-12 15:57:18.127417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12154eb07460'
down_revision: Union[str, Sequence[str], None] = '482cd8b4ee1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_trait_derivations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steam_app_id', sa.BigInteger(), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('derivation_version', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('facts_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('derived_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('story_focus_value', sa.Integer(), nullable=True),
    sa.Column('story_focus_confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('combat_intensity_value', sa.Integer(), nullable=True),
    sa.Column('combat_intensity_confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('difficulty_value', sa.Integer(), nullable=True),
    sa.Column('difficulty_confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('pacing_value', sa.Integer(), nullable=True),
    sa.Column('pacing_confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('session_friendliness_value', sa.Integer(), nullable=True),
    sa.Column('session_friendliness_confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('exploration_focus_value', sa.Integer(), nullable=True),
    sa.Column('exploration_focus_confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.CheckConstraint('(combat_intensity_value IS NULL AND combat_intensity_confidence = 0) OR (combat_intensity_value IS NOT NULL AND combat_intensity_value BETWEEN 0 AND 5 AND combat_intensity_confidence BETWEEN 0.30 AND 1)', name='ck_game_trait_derivations_combat_intensity_state'),
    sa.CheckConstraint('(difficulty_value IS NULL AND difficulty_confidence = 0) OR (difficulty_value IS NOT NULL AND difficulty_value BETWEEN 0 AND 5 AND difficulty_confidence BETWEEN 0.30 AND 1)', name='ck_game_trait_derivations_difficulty_state'),
    sa.CheckConstraint('(exploration_focus_value IS NULL AND exploration_focus_confidence = 0) OR (exploration_focus_value IS NOT NULL AND exploration_focus_value BETWEEN 0 AND 5 AND exploration_focus_confidence BETWEEN 0.30 AND 1)', name='ck_game_trait_derivations_exploration_focus_state'),
    sa.CheckConstraint('(pacing_value IS NULL AND pacing_confidence = 0) OR (pacing_value IS NOT NULL AND pacing_value BETWEEN 0 AND 5 AND pacing_confidence BETWEEN 0.30 AND 1)', name='ck_game_trait_derivations_pacing_state'),
    sa.CheckConstraint('(session_friendliness_value IS NULL AND session_friendliness_confidence = 0) OR (session_friendliness_value IS NOT NULL AND session_friendliness_value BETWEEN 0 AND 5 AND session_friendliness_confidence BETWEEN 0.30 AND 1)', name='ck_game_trait_derivations_session_friendliness_state'),
    sa.CheckConstraint('(story_focus_value IS NULL AND story_focus_confidence = 0) OR (story_focus_value IS NOT NULL AND story_focus_value BETWEEN 0 AND 5 AND story_focus_confidence BETWEEN 0.30 AND 1)', name='ck_game_trait_derivations_story_focus_state'),
    sa.CheckConstraint('length(facts_fingerprint) = 64', name='ck_game_trait_derivations_fingerprint_length'),
    sa.ForeignKeyConstraint(['steam_app_id'], ['games.steam_app_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steam_app_id', 'id', name='uq_game_trait_derivations_game_id')
    )
    op.create_index('ix_game_trait_derivations_game_derived_at', 'game_trait_derivations', ['steam_app_id', 'derived_at'], unique=False)
    op.create_table('game_current_trait_derivations',
    sa.Column('steam_app_id', sa.BigInteger(), nullable=False),
    sa.Column('derivation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['steam_app_id', 'derivation_id'], ['game_trait_derivations.steam_app_id', 'game_trait_derivations.id'], name='fk_current_trait_derivations_matching_derivation', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['steam_app_id'], ['games.steam_app_id'], name='fk_current_trait_derivations_game', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('steam_app_id'),
    sa.UniqueConstraint('derivation_id', name='uq_current_trait_derivations_derivation_id')
    )
    op.create_table('game_trait_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steam_app_id', sa.BigInteger(), nullable=False),
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('derivation_version', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('facts_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('derivation_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("(outcome = 'succeeded' AND derivation_id IS NOT NULL AND error_code IS NULL AND error_message IS NULL) OR (outcome <> 'succeeded' AND derivation_id IS NULL AND error_message IS NOT NULL)", name='ck_game_trait_attempts_result_state'),
    sa.CheckConstraint("outcome IN ('succeeded', 'transient_failure', 'invalid_response', 'authentication_failure', 'configuration_failure', 'unexpected_failure')", name='ck_game_trait_attempts_outcome'),
    sa.CheckConstraint('attempt_number >= 1', name='ck_game_trait_attempts_attempt_number'),
    sa.CheckConstraint('completed_at >= started_at', name='ck_game_trait_attempts_time_order'),
    sa.CheckConstraint('length(facts_fingerprint) = 64', name='ck_game_trait_attempts_fingerprint_length'),
    sa.ForeignKeyConstraint(['steam_app_id', 'derivation_id'], ['game_trait_derivations.steam_app_id', 'game_trait_derivations.id'], name='fk_game_trait_attempts_matching_derivation', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['steam_app_id'], ['games.steam_app_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id', 'attempt_number', name='uq_game_trait_attempts_operation_attempt')
    )
    op.create_index('ix_game_trait_attempts_game_started_at', 'game_trait_attempts', ['steam_app_id', 'started_at'], unique=False)
    op.create_table('game_trait_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('derivation_id', sa.Integer(), nullable=False),
    sa.Column('target_kind', sa.String(length=10), nullable=False),
    sa.Column('target_name', sa.String(length=30), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source_field', sa.String(length=30), nullable=False),
    sa.Column('source_value', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.CheckConstraint("(target_kind = 'trait' AND target_name IN ('story_focus', 'combat_intensity', 'difficulty', 'pacing', 'session_friendliness', 'exploration_focus')) OR (target_kind = 'mood' AND target_name IN ('relaxing', 'tense', 'emotional', 'humorous', 'dark'))", name='ck_game_trait_evidence_target'),
    sa.CheckConstraint("source_field IN ('summary', 'genre', 'theme', 'keyword', 'game_mode', 'time_to_beat', 'release_information')", name='ck_game_trait_evidence_source_field'),
    sa.CheckConstraint('length(reason) BETWEEN 1 AND 200', name='ck_game_trait_evidence_reason_length'),
    sa.CheckConstraint('length(source_value) BETWEEN 1 AND 200', name='ck_game_trait_evidence_source_value_length'),
    sa.CheckConstraint('position BETWEEN 0 AND 2', name='ck_game_trait_evidence_position'),
    sa.ForeignKeyConstraint(['derivation_id'], ['game_trait_derivations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('derivation_id', 'target_kind', 'target_name', 'position', name='uq_game_trait_evidence_target_position')
    )
    op.create_index(op.f('ix_game_trait_evidence_derivation_id'), 'game_trait_evidence', ['derivation_id'], unique=False)
    op.create_table('game_trait_moods',
    sa.Column('derivation_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.CheckConstraint("label IN ('relaxing', 'tense', 'emotional', 'humorous', 'dark')", name='ck_game_trait_moods_label'),
    sa.CheckConstraint('confidence BETWEEN 0.30 AND 1', name='ck_game_trait_moods_confidence'),
    sa.ForeignKeyConstraint(['derivation_id'], ['game_trait_derivations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('derivation_id', 'label')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_trait_moods')
    op.drop_index(op.f('ix_game_trait_evidence_derivation_id'), table_name='game_trait_evidence')
    op.drop_table('game_trait_evidence')
    op.drop_index('ix_game_trait_attempts_game_started_at', table_name='game_trait_attempts')
    op.drop_table('game_trait_attempts')
    op.drop_table('game_current_trait_derivations')
    op.drop_index('ix_game_trait_derivations_game_derived_at', table_name='game_trait_derivations')
    op.drop_table('game_trait_derivations')
    # ### end Alembic commands ###
