"""add IGDB metadata

Revision ID: 482cd8b4ee1b
Revises: a239bf0112b9
Create Date: 2026-08-08 23:24:21.202325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '482cd8b4ee1b'
down_revision: Union[str, Sequence[str], None] = 'a239bf0112b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('igdb_metadata_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('igdb_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.CheckConstraint("kind IN ('genre', 'theme', 'keyword', 'game_mode')", name='ck_igdb_metadata_terms_kind'),
    sa.CheckConstraint('igdb_id > 0', name='ck_igdb_metadata_terms_igdb_id_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'igdb_id', name='uq_igdb_metadata_terms_kind_igdb_id')
    )
    op.create_index('ix_igdb_metadata_terms_kind_name', 'igdb_metadata_terms', ['kind', 'name'], unique=False)
    op.create_table('game_igdb_metadata_terms',
    sa.Column('steam_app_id', sa.BigInteger(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['steam_app_id'], ['games.steam_app_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['igdb_metadata_terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('steam_app_id', 'term_id')
    )
    op.create_index('ix_game_igdb_metadata_terms_term_id', 'game_igdb_metadata_terms', ['term_id'], unique=False)
    op.add_column('games', sa.Column('igdb_game_id', sa.BigInteger(), nullable=True))
    op.add_column('games', sa.Column('igdb_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('games', sa.Column('igdb_last_attempted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('games', sa.Column('igdb_last_error', sa.String(length=500), nullable=True))
    op.add_column('games', sa.Column('igdb_enriched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('games', sa.Column('igdb_metadata_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('games', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('first_release_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('games', sa.Column('cover_image_id', sa.String(length=100), nullable=True))
    op.add_column('games', sa.Column('time_to_beat_hastily_seconds', sa.BigInteger(), nullable=True))
    op.add_column('games', sa.Column('time_to_beat_normally_seconds', sa.BigInteger(), nullable=True))
    op.add_column('games', sa.Column('time_to_beat_completely_seconds', sa.BigInteger(), nullable=True))
    op.add_column('games', sa.Column('time_to_beat_submission_count', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('time_to_beat_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_check_constraint(
        'ck_games_igdb_status',
        'games',
        "igdb_status IN ('pending', 'ready', 'missing', 'ambiguous')",
    )
    op.create_check_constraint(
        'ck_games_igdb_game_id_positive',
        'games',
        'igdb_game_id IS NULL OR igdb_game_id > 0',
    )
    op.create_check_constraint(
        'ck_games_hastily_seconds_nonnegative',
        'games',
        'time_to_beat_hastily_seconds IS NULL '
        'OR time_to_beat_hastily_seconds >= 0',
    )
    op.create_check_constraint(
        'ck_games_normally_seconds_nonnegative',
        'games',
        'time_to_beat_normally_seconds IS NULL '
        'OR time_to_beat_normally_seconds >= 0',
    )
    op.create_check_constraint(
        'ck_games_completely_seconds_nonnegative',
        'games',
        'time_to_beat_completely_seconds IS NULL '
        'OR time_to_beat_completely_seconds >= 0',
    )
    op.create_check_constraint(
        'ck_games_time_submission_count_nonnegative',
        'games',
        'time_to_beat_submission_count IS NULL '
        'OR time_to_beat_submission_count >= 0',
    )
    op.create_index(op.f('ix_games_igdb_game_id'), 'games', ['igdb_game_id'], unique=False)
    op.create_index(op.f('ix_games_igdb_status'), 'games', ['igdb_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_igdb_status'), table_name='games')
    op.drop_index(op.f('ix_games_igdb_game_id'), table_name='games')
    op.drop_constraint(
        'ck_games_time_submission_count_nonnegative',
        'games',
        type_='check',
    )
    op.drop_constraint(
        'ck_games_completely_seconds_nonnegative',
        'games',
        type_='check',
    )
    op.drop_constraint(
        'ck_games_normally_seconds_nonnegative',
        'games',
        type_='check',
    )
    op.drop_constraint(
        'ck_games_hastily_seconds_nonnegative',
        'games',
        type_='check',
    )
    op.drop_constraint(
        'ck_games_igdb_game_id_positive',
        'games',
        type_='check',
    )
    op.drop_constraint(
        'ck_games_igdb_status',
        'games',
        type_='check',
    )
    op.drop_column('games', 'time_to_beat_updated_at')
    op.drop_column('games', 'time_to_beat_submission_count')
    op.drop_column('games', 'time_to_beat_completely_seconds')
    op.drop_column('games', 'time_to_beat_normally_seconds')
    op.drop_column('games', 'time_to_beat_hastily_seconds')
    op.drop_column('games', 'cover_image_id')
    op.drop_column('games', 'first_release_at')
    op.drop_column('games', 'summary')
    op.drop_column('games', 'igdb_metadata_updated_at')
    op.drop_column('games', 'igdb_enriched_at')
    op.drop_column('games', 'igdb_last_error')
    op.drop_column('games', 'igdb_last_attempted_at')
    op.drop_column('games', 'igdb_status')
    op.drop_column('games', 'igdb_game_id')
    op.drop_index('ix_game_igdb_metadata_terms_term_id', table_name='game_igdb_metadata_terms')
    op.drop_table('game_igdb_metadata_terms')
    op.drop_index('ix_igdb_metadata_terms_kind_name', table_name='igdb_metadata_terms')
    op.drop_table('igdb_metadata_terms')
    # ### end Alembic commands ###
