"""add profiles and steam libraries

Revision ID: a239bf0112b9
Revises: cfafdeae2044
Create Date: 2026-07-31 21:17:25.290370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a239bf0112b9'
down_revision: Union[str, Sequence[str], None] = 'cfafdeae2044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
                    sa.Column('steam_app_id', sa.BigInteger(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('icon_url', sa.String(
                        length=500), nullable=True),
                    sa.PrimaryKeyConstraint('steam_app_id')
                    )
    op.create_table('profiles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('steam_id', sa.String(
                        length=20), nullable=False),
                    sa.Column('display_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('profile_url', sa.String(
                        length=500), nullable=True),
                    sa.Column('avatar_url', sa.String(
                        length=500), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('last_synced_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_profiles_steam_id'),
                    'profiles', ['steam_id'], unique=True)
    op.create_table('profile_games',
                    sa.Column('profile_id', sa.Integer(), nullable=False),
                    sa.Column('steam_app_id', sa.BigInteger(), nullable=False),
                    sa.Column('playtime_minutes', sa.BigInteger(),
                              server_default='0', nullable=False),
                    sa.Column('recent_playtime_minutes',
                              sa.BigInteger(), nullable=True),
                    sa.Column('last_played_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['profile_id'], ['profiles.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['steam_app_id'], ['games.steam_app_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('profile_id', 'steam_app_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_games')
    op.drop_index(op.f('ix_profiles_steam_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_table('games')
    # ### end Alembic commands ###
